language: node_js
node_js:
  - "6"
install:
  - npm install -g bower
  - npm install -g coffee-script
  - npm install
sudo: false
cache:
  directories:
  - node_modules
  - test/project/node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8


