language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-express-develop' ]; then cd .. && eval "mv $currentfolder generator-express-develop" && cd generator-express-develop; fi

